### PR TITLE
Update to CI 4.4.2

### PR DESCRIPTION
**Pull request by kenjis**
- add tatter/patches
- update app/
- update to CI 4.4.2
- update github workflows

### CODE REVIEW

**Comment by kenjis** [comment]
Why error?

```
Run composer-unused -vvv --output-format=github --ansi --no-interaction --no-progress
  

Box Requirements Checker
========================

> Using PHP 8.1.24
> PHP is using the following php.ini file:
  /etc/php/8.1/cli/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.4 || ^8.0" or greater.
  ✔ The application requires the extension "json".
  ✔ The package "nikic/php-parser" requires the extension "tokenizer".
  
                                                                                
 [OK] Your system is ready to run the application.                              
                                                                                

::error file=/home/runner/work/playground/playground/composer.json,line=25,col=0::php is unused
file=/home/runner/work/playground/playground/composer.json,line=26,col=0::codeigniter4/framework was ignored
Error: Process completed with exit code 1.
```

**Comment by MGatner** [comment]
That "PHP is unused" error keeps coming back 🙄 Ignoring it is a good workaround.

**Comment by MGatner** [comment]
Typo in your last commit message, FYI

**Review by MGatner — APPROVED** [review]
I flipped through the changes but I'm going to trust Patches and the pipeline on this.

**Pull request merged**
