### PR TITLE
Update to use RectorConfig

### PR DESCRIPTION
**Pull request by samsonasik**
ref https://getrector.org/blog/new-in-rector-012-introducing-rector-config-with-autocomplete

### CODE REVIEW

**Comment by samsonasik** [comment]
composer.lock seems needs to be generated from php 7.3

**Comment by samsonasik** [comment]
I tried to run composer update with php 7.3 and got error:

```
 php73 /usr/local/bin/composer update
Composer is operating significantly slower than normal because you do not have the PHP curl extension enabled.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires codeigniter4/codeigniter4 dev-develop -> satisfiable by codeigniter4/codeigniter4[dev-develop].
    - codeigniter4/codeigniter4 dev-develop requires php ^7.4 || ^8.0 -> your php version (7.3.33) does not satisfy that requirement.

Use the option --with-all-dependencies (-W) to a
```

**Comment by samsonasik** [comment]
I've updated requirement to php 7.4 since it require codeigniter4 dev-develop.

**Comment by samsonasik** [comment]
All green 🎉

**Comment by MGatner** [comment]
We'll switch this over to DevKit, which will include changing to `codeigniter4/framework` - but this is good and needed to happen either way.

**Review by MGatner — APPROVED** [review]

**Pull request merged**
