### PR TITLE
New simple home page to display basic data. Feature tests for page.

### PR DESCRIPTION
**Pull request by lonnieezell**

### CODE REVIEW

**Comment by lonnieezell** [comment]
I don't love having to copy over FeatureTestCase, but with the custom DatabaseTestCase already setup, I needed it to extend that, so ...

**Comment by MGatner** [comment]
This is great! Good stuff and very nicely commented. 

FeatureTestCase... that’s actually a bug, glad you found it! `SUPPORTPATH` in bootstrap is supposed to link out to the framework test, *not* project. I will merge this for now and fix ProjectTests and then make that change here as wel.

**Comment by MGatner** [comment]
I think we’ll need a better database solution so the file doesn’t get changes merged and can always be blank. I’ll do some testing to see if the file actually needs to exist for the SQLite driver to point to that location.

**Comment by lonnieezell** [comment]
OH, yeah - my bad! Didn't mean to commit changes to the database file.

**Pull request merged**
